url: http://mbmccormick.com
title: Matt McCormick
description: I'm a Program Manager at Microsoft and a Computer Science graduate from Purdue University. I live in Seattle with my fiancé and I'm always hacking away on something.
language: en-us

author: Matt McCormick
email: matt@mbmccormick.com

github: mbmccormick
twitter: mbmccormick

analytics:
    profile: 12345

permalink: /:year/:month/:title

sitemap:
    include: ["/index.html"]

exclude: ["README.md"]
