url: http://mbmccormick.com
title: Matt McCormick
description: 
language: en-us

author: Matt McCormick
email: matt@mbmccormick.com
github: mbmccormick
twitter: mbmccormick
dribbble: mbmccormick
google: mbmccormick
flattr:
    user: ptz0n
    language: sv_SE
facebook:
    app: 12345
    posts: 5
    width: 500
    admins: 12345
analytics:
    profile: 12345

permalink: /post/:title.html

future: false
auto: true
server: true

sitemap:
    include: ["/index.html"]

exclude: ["README.md", "config.rb"]
